version: "3.8"

services:
  consulta-ncm:
    build: .
    container_name: consulta-ncm
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - BASE_PATH=/ccpf
